### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JuanGonzalezCaminero** [JuanGonzalezCaminero/Tab_grouping_chrome_extension#1]
- [ ] Block group creation with no name
- [ ] Block group creation with duplicated name
- [ ] Close group when clicking the button a second time
- [ ] Tab launch button
- [ ] General styling
